# One image, three stages: the React interface, the Go binary, assembly.
# The application is STATELESS — accounts, statuses and notes live in
# PostgreSQL (PARAPHE_DATABASE_URL, provided at deployment). No volume.

FROM node:24-alpine AS interface
RUN corepack enable
# the repository tree is preserved: the interface imports the core, the
# templates and GUIDE.md from the root — a single source for the
# application, the mass mailing and the repository
WORKDIR /src
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY web/package.json web/
COPY outils/package.json outils/
RUN pnpm install --frozen-lockfile
COPY GUIDE.md ./
COPY noyau/ noyau/
COPY modeles/ modeles/
COPY web/ web/
# the API serves the interface at the root, unlike the Pages publication
ENV PARAPHE_BASE_PATH=/
# Build only — the suite does NOT run here. release.yml runs the whole CI as
# a gate before it publishes anything, so testing again inside the image adds
# no proof; and the release build is multi-arch, so the second architecture
# ran the browser suite under QEMU emulation, six times slower, where the
# 5 s test timeouts expired and the publication failed on green code.
RUN cd web && pnpm build

FROM golang:1.26-alpine AS binary
WORKDIR /src
COPY api/go.mod api/go.sum ./
RUN go mod download
COPY api/ ./
# static: the final image has no libc to offer
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /paraphe-api .

FROM alpine:3.22
RUN adduser -S -u 10001 -h /srv/paraphe paraphe
WORKDIR /srv/paraphe

COPY --from=binary /paraphe-api /usr/local/bin/paraphe-api
COPY --from=interface /src/web/dist web/dist
COPY config/ config/
COPY modeles/ modeles/
# generated by `task build`: the image embeds the mayor list of the moment.
# 04 is the one the application serves; 01 feeds the mass mailing.
COPY out/04_base_complete.csv out/04_base_complete.csv
COPY out/01_maires_cibles_prioritaires.csv out/01_maires_cibles_prioritaires.csv

ENV PARAPHE_HOST=0.0.0.0 \
    PARAPHE_PORT=8047
EXPOSE 8047

USER 10001
ENTRYPOINT ["paraphe-api"]
