// Demo dataset — INVENTED communes and officials.
// No real data here: publishing a directory of elected officials as a
// static file is precisely what this project refuses to do.

export const DEMO_SET = [
  {
    rank: "has_endorsed",
    rank_label: "A déjà parrainé un candidat peu médiatisé",
    score: "3",
    priority: "P1",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique1",
    last_name: "MARTIN1",
    commune: "Sainte-Fiction-1",
    department: "Aveyron",
    insee_code: "90001",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "Alex Exemple",
    recent_year: "2022",
    email: "mairie1@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "1 place de la Fiction",
    postal_code: "10001",
    city: "Sainte-Fiction-1",
    website: "",
    contact_form: "",
  },
  {
    rank: "has_endorsed",
    rank_label: "A déjà parrainé un candidat peu médiatisé",
    score: "3",
    priority: "P1",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique2",
    last_name: "MARTIN2",
    commune: "Sainte-Fiction-2",
    department: "Cantal",
    insee_code: "90002",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "Alex Exemple",
    recent_year: "2022",
    email: "mairie2@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "2 place de la Fiction",
    postal_code: "10002",
    city: "Sainte-Fiction-2",
    website: "",
    contact_form: "",
  },
  {
    rank: "has_endorsed",
    rank_label: "A déjà parrainé un candidat peu médiatisé",
    score: "3",
    priority: "P1",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille3",
    last_name: "MARTIN3",
    commune: "Sainte-Fiction-3",
    department: "Aveyron",
    insee_code: "90003",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "Alex Exemple",
    recent_year: "2022",
    email: "mairie3@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "3 place de la Fiction",
    postal_code: "10003",
    city: "Sainte-Fiction-3",
    website: "",
    contact_form: "",
  },
  {
    rank: "has_endorsed",
    rank_label: "A déjà parrainé un candidat peu médiatisé",
    score: "3",
    priority: "P1",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique4",
    last_name: "MARTIN4",
    commune: "Sainte-Fiction-4",
    department: "Cantal",
    insee_code: "90004",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "Alex Exemple",
    recent_year: "2022",
    email: "mairie4@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "4 place de la Fiction",
    postal_code: "10004",
    city: "Sainte-Fiction-4",
    website: "",
    contact_form: "",
  },
  {
    rank: "has_endorsed",
    rank_label: "A déjà parrainé un candidat peu médiatisé",
    score: "3",
    priority: "P1",
    democratic_theme_endorsement: "oui",
    title: "M.",
    first_name: "Dominique5",
    last_name: "MARTIN5",
    commune: "Sainte-Fiction-5",
    department: "Aveyron",
    insee_code: "90005",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "Alex Exemple",
    recent_year: "2022",
    email: "mairie5@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "5 place de la Fiction",
    postal_code: "10005",
    city: "Sainte-Fiction-5",
    website: "",
    contact_form: "",
  },
  {
    rank: "has_endorsed",
    rank_label: "A déjà parrainé un candidat peu médiatisé",
    score: "3",
    priority: "P1",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille6",
    last_name: "MARTIN6",
    commune: "Sainte-Fiction-6",
    department: "Cantal",
    insee_code: "90006",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "Alex Exemple",
    recent_year: "2022",
    email: "mairie6@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "6 place de la Fiction",
    postal_code: "10006",
    city: "Sainte-Fiction-6",
    website: "",
    contact_form: "",
  },
  {
    rank: "has_endorsed",
    rank_label: "A déjà parrainé un candidat peu médiatisé",
    score: "3",
    priority: "P1",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique7",
    last_name: "MARTIN7",
    commune: "Sainte-Fiction-7",
    department: "Aveyron",
    insee_code: "90007",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "Alex Exemple",
    recent_year: "2022",
    email: "mairie7@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "7 place de la Fiction",
    postal_code: "10007",
    city: "Sainte-Fiction-7",
    website: "",
    contact_form: "",
  },
  {
    rank: "has_endorsed",
    rank_label: "A déjà parrainé un candidat peu médiatisé",
    score: "3",
    priority: "P1",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique8",
    last_name: "MARTIN8",
    commune: "Sainte-Fiction-8",
    department: "Cantal",
    insee_code: "90008",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "Alex Exemple",
    recent_year: "2022",
    email: "mairie8@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "8 place de la Fiction",
    postal_code: "10008",
    city: "Sainte-Fiction-8",
    website: "",
    contact_form: "",
  },
  {
    rank: "has_endorsed",
    rank_label: "A déjà parrainé un candidat peu médiatisé",
    score: "3",
    priority: "P1",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille9",
    last_name: "MARTIN9",
    commune: "Sainte-Fiction-9",
    department: "Aveyron",
    insee_code: "90009",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "Alex Exemple",
    recent_year: "2022",
    email: "mairie9@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "9 place de la Fiction",
    postal_code: "10009",
    city: "Sainte-Fiction-9",
    website: "",
    contact_form: "",
  },
  {
    rank: "has_endorsed",
    rank_label: "A déjà parrainé un candidat peu médiatisé",
    score: "3",
    priority: "P1",
    democratic_theme_endorsement: "oui",
    title: "M.",
    first_name: "Dominique10",
    last_name: "MARTIN10",
    commune: "Sainte-Fiction-10",
    department: "Cantal",
    insee_code: "90010",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "Alex Exemple",
    recent_year: "2022",
    email: "mairie10@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "10 place de la Fiction",
    postal_code: "10010",
    city: "Sainte-Fiction-10",
    website: "",
    contact_form: "",
  },
  {
    rank: "has_endorsed",
    rank_label: "A déjà parrainé un candidat peu médiatisé",
    score: "3",
    priority: "P1",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique11",
    last_name: "MARTIN11",
    commune: "Sainte-Fiction-11",
    department: "Aveyron",
    insee_code: "90011",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "Alex Exemple",
    recent_year: "2022",
    email: "mairie11@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "11 place de la Fiction",
    postal_code: "10011",
    city: "Sainte-Fiction-11",
    website: "",
    contact_form: "",
  },
  {
    rank: "has_endorsed",
    rank_label: "A déjà parrainé un candidat peu médiatisé",
    score: "3",
    priority: "P1",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille12",
    last_name: "MARTIN12",
    commune: "Sainte-Fiction-12",
    department: "Cantal",
    insee_code: "90012",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "Alex Exemple",
    recent_year: "2022",
    email: "mairie12@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "12 place de la Fiction",
    postal_code: "10012",
    city: "Sainte-Fiction-12",
    website: "",
    contact_form: "",
  },
  {
    rank: "commune_has_endorsed",
    rank_label: "Sa commune l'a déjà fait (maire différent depuis)",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique13",
    last_name: "MARTIN13",
    commune: "Sainte-Fiction-13",
    department: "Aveyron",
    insee_code: "90013",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "Claude ANCIEN13",
    predecessor_mayor: "oui",
    recent_candidate: "",
    recent_year: "",
    email: "mairie13@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "13 place de la Fiction",
    postal_code: "10013",
    city: "Sainte-Fiction-13",
    website: "",
    contact_form: "",
  },
  {
    rank: "commune_has_endorsed",
    rank_label: "Sa commune l'a déjà fait (maire différent depuis)",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique14",
    last_name: "MARTIN14",
    commune: "Sainte-Fiction-14",
    department: "Cantal",
    insee_code: "90014",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "Claude ANCIEN14",
    predecessor_mayor: "oui",
    recent_candidate: "",
    recent_year: "",
    email: "mairie14@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "14 place de la Fiction",
    postal_code: "10014",
    city: "Sainte-Fiction-14",
    website: "",
    contact_form: "",
  },
  {
    rank: "commune_has_endorsed",
    rank_label: "Sa commune l'a déjà fait (maire différent depuis)",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille15",
    last_name: "MARTIN15",
    commune: "Sainte-Fiction-15",
    department: "Aveyron",
    insee_code: "90015",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "Claude ANCIEN15",
    predecessor_mayor: "oui",
    recent_candidate: "",
    recent_year: "",
    email: "mairie15@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "15 place de la Fiction",
    postal_code: "10015",
    city: "Sainte-Fiction-15",
    website: "",
    contact_form: "",
  },
  {
    rank: "commune_has_endorsed",
    rank_label: "Sa commune l'a déjà fait (maire différent depuis)",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique16",
    last_name: "MARTIN16",
    commune: "Sainte-Fiction-16",
    department: "Cantal",
    insee_code: "90016",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "Claude ANCIEN16",
    predecessor_mayor: "oui",
    recent_candidate: "",
    recent_year: "",
    email: "mairie16@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "16 place de la Fiction",
    postal_code: "10016",
    city: "Sainte-Fiction-16",
    website: "",
    contact_form: "",
  },
  {
    rank: "commune_has_endorsed",
    rank_label: "Sa commune l'a déjà fait (maire différent depuis)",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique17",
    last_name: "MARTIN17",
    commune: "Sainte-Fiction-17",
    department: "Aveyron",
    insee_code: "90017",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "Claude ANCIEN17",
    predecessor_mayor: "oui",
    recent_candidate: "",
    recent_year: "",
    email: "mairie17@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "17 place de la Fiction",
    postal_code: "10017",
    city: "Sainte-Fiction-17",
    website: "",
    contact_form: "",
  },
  {
    rank: "commune_has_endorsed",
    rank_label: "Sa commune l'a déjà fait (maire différent depuis)",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille18",
    last_name: "MARTIN18",
    commune: "Sainte-Fiction-18",
    department: "Cantal",
    insee_code: "90018",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "Claude ANCIEN18",
    predecessor_mayor: "oui",
    recent_candidate: "",
    recent_year: "",
    email: "mairie18@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "18 place de la Fiction",
    postal_code: "10018",
    city: "Sainte-Fiction-18",
    website: "",
    contact_form: "",
  },
  {
    rank: "commune_has_endorsed",
    rank_label: "Sa commune l'a déjà fait (maire différent depuis)",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique19",
    last_name: "MARTIN19",
    commune: "Sainte-Fiction-19",
    department: "Aveyron",
    insee_code: "90019",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "Claude ANCIEN19",
    predecessor_mayor: "oui",
    recent_candidate: "",
    recent_year: "",
    email: "mairie19@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "19 place de la Fiction",
    postal_code: "10019",
    city: "Sainte-Fiction-19",
    website: "",
    contact_form: "",
  },
  {
    rank: "commune_has_endorsed",
    rank_label: "Sa commune l'a déjà fait (maire différent depuis)",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique20",
    last_name: "MARTIN20",
    commune: "Sainte-Fiction-20",
    department: "Cantal",
    insee_code: "90020",
    endorsement_history: "2017: EXEMPLE Alex (A) | 2022: EXEMPLE Alex (A)",
    predecessor: "Claude ANCIEN20",
    predecessor_mayor: "oui",
    recent_candidate: "",
    recent_year: "",
    email: "mairie20@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "20 place de la Fiction",
    postal_code: "10020",
    city: "Sainte-Fiction-20",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille21",
    last_name: "MARTIN21",
    commune: "Sainte-Fiction-21",
    department: "Aveyron",
    insee_code: "90021",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie21@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "21 place de la Fiction",
    postal_code: "10021",
    city: "Sainte-Fiction-21",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique22",
    last_name: "MARTIN22",
    commune: "Sainte-Fiction-22",
    department: "Cantal",
    insee_code: "90022",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie22@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "22 place de la Fiction",
    postal_code: "10022",
    city: "Sainte-Fiction-22",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique23",
    last_name: "MARTIN23",
    commune: "Sainte-Fiction-23",
    department: "Aveyron",
    insee_code: "90023",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie23@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "23 place de la Fiction",
    postal_code: "10023",
    city: "Sainte-Fiction-23",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille24",
    last_name: "MARTIN24",
    commune: "Sainte-Fiction-24",
    department: "Cantal",
    insee_code: "90024",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie24@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "24 place de la Fiction",
    postal_code: "10024",
    city: "Sainte-Fiction-24",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique25",
    last_name: "MARTIN25",
    commune: "Sainte-Fiction-25",
    department: "Aveyron",
    insee_code: "90025",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie25@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "25 place de la Fiction",
    postal_code: "10025",
    city: "Sainte-Fiction-25",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique26",
    last_name: "MARTIN26",
    commune: "Sainte-Fiction-26",
    department: "Cantal",
    insee_code: "90026",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie26@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "26 place de la Fiction",
    postal_code: "10026",
    city: "Sainte-Fiction-26",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille27",
    last_name: "MARTIN27",
    commune: "Sainte-Fiction-27",
    department: "Aveyron",
    insee_code: "90027",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie27@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "27 place de la Fiction",
    postal_code: "10027",
    city: "Sainte-Fiction-27",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique28",
    last_name: "MARTIN28",
    commune: "Sainte-Fiction-28",
    department: "Cantal",
    insee_code: "90028",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie28@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "28 place de la Fiction",
    postal_code: "10028",
    city: "Sainte-Fiction-28",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique29",
    last_name: "MARTIN29",
    commune: "Sainte-Fiction-29",
    department: "Aveyron",
    insee_code: "90029",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie29@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "29 place de la Fiction",
    postal_code: "10029",
    city: "Sainte-Fiction-29",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille30",
    last_name: "MARTIN30",
    commune: "Sainte-Fiction-30",
    department: "Cantal",
    insee_code: "90030",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie30@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "30 place de la Fiction",
    postal_code: "10030",
    city: "Sainte-Fiction-30",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique31",
    last_name: "MARTIN31",
    commune: "Sainte-Fiction-31",
    department: "Aveyron",
    insee_code: "90031",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie31@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "31 place de la Fiction",
    postal_code: "10031",
    city: "Sainte-Fiction-31",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique32",
    last_name: "MARTIN32",
    commune: "Sainte-Fiction-32",
    department: "Cantal",
    insee_code: "90032",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie32@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "32 place de la Fiction",
    postal_code: "10032",
    city: "Sainte-Fiction-32",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille33",
    last_name: "MARTIN33",
    commune: "Sainte-Fiction-33",
    department: "Aveyron",
    insee_code: "90033",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie33@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "33 place de la Fiction",
    postal_code: "10033",
    city: "Sainte-Fiction-33",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique34",
    last_name: "MARTIN34",
    commune: "Sainte-Fiction-34",
    department: "Cantal",
    insee_code: "90034",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie34@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "34 place de la Fiction",
    postal_code: "10034",
    city: "Sainte-Fiction-34",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique35",
    last_name: "MARTIN35",
    commune: "Sainte-Fiction-35",
    department: "Aveyron",
    insee_code: "90035",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie35@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "35 place de la Fiction",
    postal_code: "10035",
    city: "Sainte-Fiction-35",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille36",
    last_name: "MARTIN36",
    commune: "Sainte-Fiction-36",
    department: "Cantal",
    insee_code: "90036",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie36@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "36 place de la Fiction",
    postal_code: "10036",
    city: "Sainte-Fiction-36",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique37",
    last_name: "MARTIN37",
    commune: "Sainte-Fiction-37",
    department: "Aveyron",
    insee_code: "90037",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie37@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "37 place de la Fiction",
    postal_code: "10037",
    city: "Sainte-Fiction-37",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique38",
    last_name: "MARTIN38",
    commune: "Sainte-Fiction-38",
    department: "Cantal",
    insee_code: "90038",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie38@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "38 place de la Fiction",
    postal_code: "10038",
    city: "Sainte-Fiction-38",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille39",
    last_name: "MARTIN39",
    commune: "Sainte-Fiction-39",
    department: "Aveyron",
    insee_code: "90039",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie39@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "39 place de la Fiction",
    postal_code: "10039",
    city: "Sainte-Fiction-39",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique40",
    last_name: "MARTIN40",
    commune: "Sainte-Fiction-40",
    department: "Cantal",
    insee_code: "90040",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie40@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "40 place de la Fiction",
    postal_code: "10040",
    city: "Sainte-Fiction-40",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique41",
    last_name: "MARTIN41",
    commune: "Sainte-Fiction-41",
    department: "Aveyron",
    insee_code: "90041",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie41@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "41 place de la Fiction",
    postal_code: "10041",
    city: "Sainte-Fiction-41",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille42",
    last_name: "MARTIN42",
    commune: "Sainte-Fiction-42",
    department: "Cantal",
    insee_code: "90042",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie42@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "42 place de la Fiction",
    postal_code: "10042",
    city: "Sainte-Fiction-42",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique43",
    last_name: "MARTIN43",
    commune: "Sainte-Fiction-43",
    department: "Aveyron",
    insee_code: "90043",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie43@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "43 place de la Fiction",
    postal_code: "10043",
    city: "Sainte-Fiction-43",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique44",
    last_name: "MARTIN44",
    commune: "Sainte-Fiction-44",
    department: "Cantal",
    insee_code: "90044",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie44@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "44 place de la Fiction",
    postal_code: "10044",
    city: "Sainte-Fiction-44",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille45",
    last_name: "MARTIN45",
    commune: "Sainte-Fiction-45",
    department: "Aveyron",
    insee_code: "90045",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie45@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "45 place de la Fiction",
    postal_code: "10045",
    city: "Sainte-Fiction-45",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique46",
    last_name: "MARTIN46",
    commune: "Sainte-Fiction-46",
    department: "Cantal",
    insee_code: "90046",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie46@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "46 place de la Fiction",
    postal_code: "10046",
    city: "Sainte-Fiction-46",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique47",
    last_name: "MARTIN47",
    commune: "Sainte-Fiction-47",
    department: "Aveyron",
    insee_code: "90047",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie47@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "47 place de la Fiction",
    postal_code: "10047",
    city: "Sainte-Fiction-47",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "Mme",
    first_name: "Camille48",
    last_name: "MARTIN48",
    commune: "Sainte-Fiction-48",
    department: "Cantal",
    insee_code: "90048",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie48@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "48 place de la Fiction",
    postal_code: "10048",
    city: "Sainte-Fiction-48",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique49",
    last_name: "MARTIN49",
    commune: "Sainte-Fiction-49",
    department: "Aveyron",
    insee_code: "90049",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie49@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "49 place de la Fiction",
    postal_code: "10049",
    city: "Sainte-Fiction-49",
    website: "",
    contact_form: "",
  },
  {
    rank: "no_signal",
    rank_label: "Aucun signal connu",
    score: "0",
    priority: "",
    democratic_theme_endorsement: "",
    title: "M.",
    first_name: "Dominique50",
    last_name: "MARTIN50",
    commune: "Sainte-Fiction-50",
    department: "Cantal",
    insee_code: "90050",
    endorsement_history: "",
    predecessor: "",
    predecessor_mayor: "",
    recent_candidate: "",
    recent_year: "",
    email: "mairie50@exemple-fictif.fr",
    phone: "01 23 45 67 89",
    town_hall_hours: "lundi 9h-12h",
    postal_address: "50 place de la Fiction",
    postal_code: "10050",
    city: "Sainte-Fiction-50",
    website: "",
    contact_form: "",
  },
];
