package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"strconv"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Walls between campaigns.
//
// The filter does NOT rest on the discipline of each query: review already
// found two scope holes in this very code (/export.csv, then /status), and a
// third one between organisations would leak one campaign's work into
// another. PostgreSQL therefore enforces the wall itself — ENABLE then FORCE
// ROW LEVEL SECURITY, one policy per table, and `app.org_id` set for the
// duration of the transaction at the start of every HTTP request. FORCE is
// essential: without it, the owner of the tables (the account the
// application connects with) walks past every policy.

// Tables walled off per organisation. `mayors` is not among them: the list
// is public, identical for everyone, and read-only.
var walledTables = []string{"assignments", "notes", "teams", "accounts"}

// The policy lets only the current organisation through. `current_setting`
// is called in "missing_ok" mode: with no setting, it returns NULL, the
// comparison is NULL, hence false — no rows. A transaction that forgot to
// declare itself sees nothing, instead of everything.
//
// The NULLIF is not decorative: a TRANSACTION-scoped setting does not go
// back to "absent" when the transaction ends, it becomes the EMPTY STRING.
// On a pool connection that has already served, the policy would therefore
// cast an empty string to int and raise "invalid input syntax for type
// integer" — a loud failure, but in the wrong place and with no apparent
// relation to the cause.
const currentScopeSQL = `NULLIF(current_setting('app.org_id', true), '')::int`

const orgPolicy = `org_id = ` + currentScopeSQL +
	` OR ` + currentScopeSQL + ` = ` + maintenanceSQL

// -1 in SQL: maintenance (import, migrations) traverses the organisations.
// No HTTP request can reach it — resolution only returns identifiers read
// from the database (≥ 1) or OrgInstance (0).
const maintenanceSQL = "-1"

func orgSchema(ctx context.Context, tx pgx.Tx) error {
	statements := []string{
		// PostgreSQL identities start at 1: 0 and -1 stay free for the
		// sentinel scopes (instance, maintenance)
		`CREATE TABLE IF NOT EXISTS orgs(
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			slug TEXT UNIQUE NOT NULL,
			name TEXT NOT NULL,
			campaign JSONB NOT NULL DEFAULT '{}'::jsonb,
			batch_size INTEGER NOT NULL DEFAULT 10,
			state TEXT NOT NULL DEFAULT 'active',
			created_at TEXT)`,
		// The form is public: without moderation, the first abuse is
		// squatting a candidate's name. A request therefore creates
		// nothing — it waits for an instance administrator to approve it.
		`CREATE TABLE IF NOT EXISTS hosting_requests(
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			slug TEXT NOT NULL,
			name TEXT NOT NULL,
			campaign JSONB NOT NULL DEFAULT '{}'::jsonb,
			requester_email TEXT NOT NULL,
			requester_name TEXT NOT NULL,
			message TEXT NOT NULL DEFAULT '',
			state TEXT NOT NULL DEFAULT 'pending',
			reason TEXT NOT NULL DEFAULT '',
			ts TEXT, decided_at TEXT, decided_by TEXT)`,
		`CREATE INDEX IF NOT EXISTS hosting_requests_state ON hosting_requests(state, id DESC)`,
		// The work columns move out of `mayors`: they are the only ones that
		// belong to an organisation, hence the only ones under RLS.
		`CREATE TABLE IF NOT EXISTS assignments(
			org_id INTEGER NOT NULL,
			insee_code TEXT NOT NULL,
			team_id INTEGER,
			volunteer TEXT,
			status TEXT NOT NULL DEFAULT 'to_contact',
			updated_at TEXT,
			PRIMARY KEY (org_id, insee_code))`,
		`CREATE INDEX IF NOT EXISTS assignments_volunteer ON assignments(org_id, volunteer)`,
		`CREATE INDEX IF NOT EXISTS assignments_team ON assignments(org_id, team_id)`,
	}
	for _, s := range statements {
		if _, err := tx.Exec(ctx, s); err != nil {
			return fmt.Errorf("organisation schema: %w", err)
		}
	}
	return nil
}

// enableRLS sets the policies up. Idempotent: DROP POLICY IF EXISTS then
// CREATE, because CREATE POLICY has no IF NOT EXISTS and the policy must be
// able to evolve with a simple image update.
func enableRLS(ctx context.Context, tx pgx.Tx) error {
	for _, table := range walledTables {
		statements := []string{
			fmt.Sprintf("ALTER TABLE %s ENABLE ROW LEVEL SECURITY", table),
			// FORCE: without it, the owner of the tables — that is, the
			// account the application connects with — walks past every policy
			// unnoticed, and the wall only protects against third parties.
			fmt.Sprintf("ALTER TABLE %s FORCE ROW LEVEL SECURITY", table),
			fmt.Sprintf("DROP POLICY IF EXISTS org_%s ON %s", table, table),
			fmt.Sprintf("CREATE POLICY org_%s ON %s USING (%s) WITH CHECK (%s)",
				table, table, orgPolicy, orgPolicy),
		}
		for _, s := range statements {
			if _, err := tx.Exec(ctx, s); err != nil {
				return fmt.Errorf("RLS on %s: %w", table, err)
			}
		}
	}
	return nil
}

// VerifyWalling refuses a configuration under which the walls would not
// apply.
//
// A SUPERUSER — and any BYPASSRLS role — walks through row-level security
// policies, FORCE included. The application would then run exactly as if
// RLS did not exist: queries return the right rows as long as their WHERE
// clauses are correct, and the day one of them is wrong, one campaign's
// work goes to another. Nothing would signal it — that is the silent
// failure this whole mechanism exists to rule out, and it is the default
// state: the official PostgreSQL image makes POSTGRES_USER a superuser.
func VerifyWalling(ctx context.Context, pool *pgxpool.Pool) error {
	var role string
	var privileged bool
	if err := pool.QueryRow(ctx,
		"SELECT rolname, rolsuper OR rolbypassrls FROM pg_roles "+
			"WHERE rolname = current_user").Scan(&role, &privileged); err != nil {
		return fmt.Errorf("reading the connection role's privileges: %w", err)
	}
	if !privileged {
		return nil
	}
	const remedy = "Create an unprivileged role and connect the application " +
		"with it:\n" +
		"  CREATE ROLE paraphe_app LOGIN PASSWORD '…' NOSUPERUSER NOBYPASSRLS;\n" +
		"  GRANT CREATE, USAGE ON SCHEMA public TO paraphe_app;\n" +
		"then point PARAPHE_DATABASE_URL at that role. With CloudNativePG, " +
		"the \"<cluster>-app\" secret already fits."
	if BaseDomain() != "" {
		return fmt.Errorf("the application connects with role %q, which is "+
			"SUPERUSER or BYPASSRLS: the walls between campaigns would NOT "+
			"apply, and nothing would signal it.\n%s", role, remedy)
	}
	log.Printf("WARNING: role %q walks through RLS policies (SUPERUSER or "+
		"BYPASSRLS). Harmless while the instance hosts a single campaign, but "+
		"fix it before hosting several.\n%s", role, remedy)
	return nil
}

// setOrgScope declares the transaction's scope. The third argument of
// set_config is `true`: the scope is the TRANSACTION, not the session —
// with a connection pool, a session setting would outlive the request and
// the next one would inherit the previous request's scope.
func setOrgScope(ctx context.Context, tx pgx.Tx, org int) error {
	// set_config expects text: the integer is converted here, not in the
	// SQL, since pgx otherwise infers the parameter type from the function
	// signature
	if _, err := tx.Exec(ctx,
		"SELECT set_config('app.org_id', $1, true)", strconv.Itoa(org)); err != nil {
		return fmt.Errorf("declaring the scope (organisation %d): %w", org, err)
	}
	return nil
}

// withOrgScope runs a write inside ANOTHER campaign's scope, then restores
// the request's own. A single caller needs it: approving a hosting request,
// which creates the campaign and its holder's coordination account —
// without it the organisation would exist with nobody able to enter. The
// deviation is therefore explicit, bounded to one statement, and never
// driven by client data: the scope is the organisation just created.
func withOrgScope(ctx context.Context, tx pgx.Tx, org, restore int,
	fn func() error) error {
	if err := setOrgScope(ctx, tx, org); err != nil {
		return err
	}
	if err := fn(); err != nil {
		return err
	}
	return setOrgScope(ctx, tx, restore)
}

// ensureOrg creates or refreshes the bootstrap organisation from the file
// and environment configuration. Values entered in the application by
// coordination are NOT overwritten: only the keys actually provided by the
// configuration are reapplied, so PARAPHE_CANDIDATE remains a way to fix a
// campaign without touching the database.
// nameOverride: the organisation's public name follows the candidate, and
// is only reimposed when an operator gave PARAPHE_CANDIDATE explicitly.
func nameOverride(cfg *Config) *string {
	if v, ok := cfg.Overrides["candidat"]; ok {
		return &v
	}
	return nil
}

func ensureOrg(ctx context.Context, tx pgx.Tx, slug string, cfg *Config) (int, error) {
	campaign, err := json.Marshal(cfg.Campaign)
	if err != nil {
		return 0, fmt.Errorf("serialising the campaign: %w", err)
	}
	// `a || b` in JSONB lets b win. The file config ALWAYS carries all nine
	// keys — a complete configuration requires them, and the shipped
	// campagne.toml fills them with template values — so applying it here
	// reverted, at every restart, everything coordination had typed into
	// "Mon équipe", down to re-arming the "campaign not configured" banner
	// and regenerating "Prénom NOM" messages. Only the keys an operator
	// gave explicitly through PARAPHE_* reapply themselves.
	// The same rule as the campaign keys, for the two columns beside them:
	// the batch size and the public name are edited in "Mon équipe", and
	// reapplying the file on restart put the batch back to its default
	// without a word — volunteers took ten cards where coordination had
	// asked for twenty-five.
	//
	// A nil map marshals to `null`, and `object || null` in JSONB yields an
	// ARRAY: the column stops being a campaign and every read of it fails.
	explicit := cfg.Overrides
	if explicit == nil {
		explicit = map[string]string{}
	}
	overrides, err := json.Marshal(explicit)
	if err != nil {
		return 0, fmt.Errorf("serialising the campaign overrides: %w", err)
	}
	var id int
	err = tx.QueryRow(ctx,
		"INSERT INTO orgs(slug, name, campaign, batch_size, state, created_at) "+
			"VALUES($1,$2,$3::jsonb,$4,'active',$5) "+
			"ON CONFLICT (slug) DO UPDATE SET "+
			"name=COALESCE($7, orgs.name), "+
			"campaign=orgs.campaign || $6::jsonb, "+
			"batch_size=COALESCE($8, orgs.batch_size) RETURNING id",
		slug, cfg.Campaign["candidat"], string(campaign), cfg.BatchSize,
		shortTimestamp(), string(overrides), nameOverride(cfg),
		cfg.BatchSizeOverride).Scan(&id)
	if err != nil {
		return 0, fmt.Errorf("bootstrap organisation %q: %w", slug, err)
	}
	return id, nil
}

// ReadOrg loads a campaign by its subdomain.
func (s *Server) ReadOrg(ctx context.Context, q interface {
	QueryRow(context.Context, string, ...any) pgx.Row
}, slug string) (*Org, error) {
	var o Org
	var campaign []byte
	err := q.QueryRow(ctx,
		"SELECT id, slug, name, campaign::text, batch_size, state, COALESCE(created_at,'') "+
			"FROM orgs WHERE slug=$1", slug).
		Scan(&o.ID, &o.Slug, &o.Name, &campaign, &o.BatchSize, &o.State, &o.CreatedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("reading organisation %q: %w", slug, err)
	}
	o.Campaign = map[string]string{}
	if err := json.Unmarshal(campaign, &o.Campaign); err != nil {
		return nil, fmt.Errorf("unreadable configuration for organisation %q: %w",
			slug, err)
	}
	return &o, nil
}

// slugTaken: whether a slug already designates an organisation, checked
// before approving a new hosting request.
func slugTaken(ctx context.Context, q pgx.Tx, slug string) (bool, error) {
	var taken bool
	if err := q.QueryRow(ctx,
		"SELECT EXISTS(SELECT 1 FROM orgs WHERE slug=$1)", slug).Scan(&taken); err != nil {
		return false, fmt.Errorf("looking up slug %q: %w", slug, err)
	}
	return taken, nil
}

// completeCampaign: an organisation's configuration, padded with the
// expected keys, so a template never references a missing one.
func completeCampaign(raw map[string]string) map[string]string {
	out := make(map[string]string, len(CampaignKeys))
	for _, k := range CampaignKeys {
		out[k] = strings.TrimSpace(raw[k])
	}
	return out
}
