package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
)

// Walls between campaigns.
//
// The wall IS the discipline of each query: every one touching a
// per-campaign table names the campaign, bound as $1 by the single
// constructor scoped(r). Row-level security was a second wall and was
// removed — do not reintroduce it without reopening that decision. What
// holds the remaining wall is a pair of tests:
// TestEveryQueryOnAWalledTableNamesTheCampaign reads the package as an AST
// and refuses a query that leaves a walled alias unbounded, and
// TestNoCampaignSeesAnother runs two campaigns against every route.

// Tables that carry per-campaign rows. `mayors` is not among them: the list
// is public, identical for everyone, and read-only.
//
// The wall over them is the application's: every query naming one of these
// also names the campaign, and TestEveryQueryOnAWalledTableNamesTheCampaign
// reads the package to prove it. This list is what that guard iterates, so a
// new per-campaign table is covered the day it is added here.
var walledTables = []string{
	"assignments", "notes", "teams", "accounts", "team_requests",
	"login_tokens",
}

func orgSchema(ctx context.Context, tx pgx.Tx) error {
	statements := []string{
		// PostgreSQL identities start at 1: 0 and -1 stay free for the
		// sentinel scopes (instance, maintenance)
		`CREATE TABLE IF NOT EXISTS orgs(
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			slug TEXT UNIQUE NOT NULL,
			name TEXT NOT NULL,
			campaign JSONB NOT NULL DEFAULT '{}'::jsonb,
			batch_size INTEGER NOT NULL DEFAULT 10,
			state TEXT NOT NULL DEFAULT 'active',
			created_at TEXT,
			-- Whether the apex directory lists the campaign: chosen on the
			-- hosting request, carried onto the organisation at approval, and
			-- adjustable later by its coordination — discretion is strategic
			-- for a campaign preparing its announcement.
			listed BOOLEAN NOT NULL DEFAULT TRUE,
			-- The campaign's logo, as a POINTER into the object store: no
			-- bytes, only which object should exist and what it is. That
			-- pointer is the only way an orphan — or a bucket restored from an
			-- older copy — is ever noticed. The key ENDS in a digest of the
			-- content, so a column for the digest would be the same fact
			-- written twice.
			logo_key TEXT NOT NULL DEFAULT '',
			logo_type TEXT NOT NULL DEFAULT '')`,
		// The form is public: without moderation, the first abuse is
		// squatting a candidate's name. A request therefore creates
		// nothing — it waits for an instance administrator to approve it.
		`CREATE TABLE IF NOT EXISTS hosting_requests(
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			slug TEXT NOT NULL,
			name TEXT NOT NULL,
			campaign JSONB NOT NULL DEFAULT '{}'::jsonb,
			requester_email TEXT NOT NULL,
			requester_name TEXT NOT NULL,
			message TEXT NOT NULL DEFAULT '',
			state TEXT NOT NULL DEFAULT 'pending',
			reason TEXT NOT NULL DEFAULT '',
			-- the choice the requester makes on the form, carried onto the
			-- organisation at approval
			listed BOOLEAN NOT NULL DEFAULT TRUE,
			ts TEXT, decided_at TEXT, decided_by TEXT)`,
		`CREATE INDEX IF NOT EXISTS hosting_requests_state ON hosting_requests(state, id DESC)`,
		// One pending request per address, enforced by the DATABASE. The
		// handler reads « is one pending? » and then inserts, and two clients
		// between those two statements both read no and both insert: the
		// moderation queue then shows one address twice, from a double click
		// or from two strangers a hundred milliseconds apart. The unique
		// index makes the loser of the race collide, and the handler answers
		// it the 409 it already has a message for.
		`CREATE UNIQUE INDEX IF NOT EXISTS hosting_requests_pending_slug ` +
			`ON hosting_requests(slug) WHERE state='pending'`,
		// The work columns move out of `mayors`: they are the only ones that
		// belong to an organisation, hence the only ones walled.
		`CREATE TABLE IF NOT EXISTS assignments(
			org_id INTEGER NOT NULL,
			insee_code TEXT NOT NULL,
			team_id INTEGER,
			volunteer TEXT,
			status TEXT NOT NULL DEFAULT 'to_contact',
			updated_at TEXT,
			PRIMARY KEY (org_id, insee_code))`,
		`CREATE INDEX IF NOT EXISTS assignments_volunteer ON assignments(org_id, volunteer)`,
		`CREATE INDEX IF NOT EXISTS assignments_team ON assignments(org_id, team_id)`,
		// Asking to open a local team. The form is public on a campaign and,
		// like the hosting form above it, creates NOTHING: a team carries a
		// work perimeter, and whoever leads it signs in and reads the notes of
		// everyone in it. Both are the coordination's to decide.
		`CREATE TABLE IF NOT EXISTS team_requests(
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			org_id INTEGER NOT NULL,
			name TEXT NOT NULL,
			departments TEXT NOT NULL DEFAULT '',
			requester_email TEXT NOT NULL,
			requester_name TEXT NOT NULL,
			message TEXT NOT NULL DEFAULT '',
			state TEXT NOT NULL DEFAULT 'pending',
			reason TEXT NOT NULL DEFAULT '',
			ts TEXT, decided_at TEXT, decided_by TEXT)`,
		`CREATE INDEX IF NOT EXISTS team_requests_state ON team_requests(org_id, state, id DESC)`,
		// One pending request per team name and per campaign, enforced by the
		// DATABASE for the reason the hosting queue learned: the handler reads
		// « is one pending? » and then inserts, and two clients between those
		// two statements both read no and both insert. The loser of the race
		// collides here and gets the 409 the check already has a message for.
		`CREATE UNIQUE INDEX IF NOT EXISTS team_requests_pending_name ` +
			`ON team_requests(org_id, name) WHERE state='pending'`,
	}
	for _, s := range statements {
		if _, err := tx.Exec(ctx, s); err != nil {
			return fmt.Errorf("organisation schema: %w", err)
		}
	}
	return nil
}

// ensureOrg creates or refreshes the bootstrap organisation from the file
// and environment configuration. Values entered in the application by
// coordination are NOT overwritten: only the keys actually provided by the
// configuration are reapplied, so PARAPHE_CANDIDATE remains a way to fix a
// campaign without touching the database.
// nameOverride: the organisation's public name follows the candidate, and
// is only reimposed when an operator gave PARAPHE_CANDIDATE explicitly.
func nameOverride(cfg *Config) *string {
	if v, ok := cfg.Overrides["candidat"]; ok {
		return &v
	}
	return nil
}

func ensureOrg(ctx context.Context, tx pgx.Tx, slug string, cfg *Config) (int, error) {
	campaign, err := json.Marshal(cfg.Campaign)
	if err != nil {
		return 0, fmt.Errorf("serialising the campaign: %w", err)
	}
	// `a || b` in JSONB lets b win. The file config ALWAYS carries all nine
	// keys — a complete configuration requires them, and the shipped
	// campagne.yaml fills them with template values — so applying it here
	// reverted, at every restart, everything coordination had typed into
	// "Mon équipe", down to re-arming the "campaign not configured" banner
	// and regenerating "Prénom NOM" messages. Only the keys an operator
	// gave explicitly through PARAPHE_* reapply themselves.
	// The same rule as the campaign keys, for the two columns beside them:
	// the batch size and the public name are edited in "Mon équipe", and
	// reapplying the file on restart put the batch back to its default
	// without a word — volunteers took ten cards where coordination had
	// asked for twenty-five.
	//
	// A nil map marshals to `null`, and `object || null` in JSONB yields an
	// ARRAY: the column stops being a campaign and every read of it fails.
	explicit := cfg.Overrides
	if explicit == nil {
		explicit = map[string]string{}
	}
	overrides, err := json.Marshal(explicit)
	if err != nil {
		return 0, fmt.Errorf("serialising the campaign overrides: %w", err)
	}
	var id int
	err = tx.QueryRow(ctx,
		"INSERT INTO orgs(slug, name, campaign, batch_size, state, created_at) "+
			"VALUES($1,$2,$3::jsonb,$4,'active',$5) "+
			"ON CONFLICT (slug) DO UPDATE SET "+
			"name=COALESCE($7, orgs.name), "+
			"campaign=orgs.campaign || $6::jsonb, "+
			"batch_size=COALESCE($8, orgs.batch_size) RETURNING id",
		slug, cfg.Campaign["candidat"], string(campaign), cfg.BatchSize,
		shortTimestamp(), string(overrides), nameOverride(cfg),
		cfg.BatchSizeOverride).Scan(&id)
	if err != nil {
		return 0, fmt.Errorf("bootstrap organisation %q: %w", slug, err)
	}
	return id, nil
}

// ReadOrg loads a campaign by its subdomain.
func (s *Server) ReadOrg(ctx context.Context, q interface {
	QueryRow(context.Context, string, ...any) pgx.Row
}, slug string) (*Org, error) {
	var o Org
	var campaign []byte
	err := q.QueryRow(ctx,
		"SELECT id, slug, name, campaign::text, batch_size, state, COALESCE(created_at,''), listed, "+
			"logo_key, logo_type "+
			"FROM orgs WHERE slug=$1", slug).
		Scan(&o.ID, &o.Slug, &o.Name, &campaign, &o.BatchSize, &o.State, &o.CreatedAt, &o.Listed,
			&o.LogoKey, &o.LogoType)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("reading organisation %q: %w", slug, err)
	}
	o.Campaign = map[string]string{}
	if err := json.Unmarshal(campaign, &o.Campaign); err != nil {
		return nil, fmt.Errorf("unreadable configuration for organisation %q: %w",
			slug, err)
	}
	return &o, nil
}

// slugTaken: whether a slug already designates an organisation, checked
// before approving a new hosting request.
func slugTaken(ctx context.Context, q pgx.Tx, slug string) (bool, error) {
	var taken bool
	if err := q.QueryRow(ctx,
		"SELECT EXISTS(SELECT 1 FROM orgs WHERE slug=$1)", slug).Scan(&taken); err != nil {
		return false, fmt.Errorf("looking up slug %q: %w", slug, err)
	}
	return taken, nil
}

// completeCampaign: an organisation's configuration, padded with the
// expected keys, so a template never references a missing one.
func completeCampaign(raw map[string]string) map[string]string {
	out := make(map[string]string, len(CampaignKeys))
	for _, k := range CampaignKeys {
		out[k] = strings.TrimSpace(raw[k])
	}
	return out
}
